name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: 22
        cache: npm
    - run: npm ci
    - run: npm test
    - run: npm run build
    - run: npm run lint:ext
    - uses: actions/upload-artifact@v7
      with:
        name: osm-smart-menu
        path: web-ext-artifacts/*.zip
